---
abstract: 'Task to install all POE related IRC modules.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Task-POE-IRC
no_index:
  directory:
    - inc
    - t
requires:
  POE: 1.0001
  POE::Component::Client::DNS: 1
  POE::Component::IRC: 5.74
  POE::Component::Server::IRC: 1.3
  perl: 5.6.0
tests: 't/*.t xt/*.t'
version: 1.08
